---
title: "sandbox"
output: flexdashboard::flex_dashboard
date: '2022-06-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, packages, results="hide", echo=FALSE, message = FALSE}
library(tidyverse)
library(tsibble)
library(fable)
library(GGally)
library(feasts)
library(knitr)
library(printr)
library(DT)
```
```{r, fake data, results="hide", echo=FALSE, message = FALSE}
# This is some time series data I found on the internet I transformed a bit
df <- read_csv("C:/Users/AxelTorbenson/OneDrive - eCapital Advisors, LLC/Documents/templates/CapitalForecasting/Data/working_capital_fake_data.csv")
```
```{r, tidying, results="hide", echo=FALSE}
# convert to tsibble and add working capital and current ratio
df$date <- as.Date(as.character(df$date), format = "%m/%d/%Y")
df <- df %>%
  mutate(date = yearmonth(as.character(date)),
         working_capital = working_capital) %>%
  as_tsibble(index = date)

work_cap <- df %>%
  filter(row_number() <= n() - 36) %>%
  as_tsibble(index = date)
```

# Graphs

## Column 1

### Working Capital Decomposition

```{r, decomposition, echo=FALSE, fig.width = 11, fig.height = 8}
work_cap %>%
  model(STL(working_capital ~ trend(window = 21) +
              season(window = 13),
            robust = TRUE)) %>%
  components() %>%
  autoplot() +
  labs(y = "Working Capital (millions)", x = "Date")
```

```{r, modeling, echo=FALSE}
arima_fit <- work_cap %>%
  model(# ARIMA function automatically picks best fitting model using AIC
    auto = ARIMA(working_capital, ic = 'aic', stepwise = FALSE))
# refit to all data
full_fit <- arima_fit %>%
  refit(df)
```

## Column 2

### Forecast

```{r, conf int graph, echo=FALSE, fig.width = 9}
forecast(full_fit, h = "3 year") %>%
  autoplot(filter(df, row_number() >= n() - 150), level = c(70, 95)) +
  labs(y = "Working Capital (millions)", x = "Date")
```

### Simulation

```{r, sample paths, echo=FALSE, fig.width = 9}
simulation <- generate(full_fit, h = 36, times = 5) %>%
  filter(.model == 'auto')

df %>%
  filter(row_number() >= n() - 150) %>%
  autoplot(working_capital) + autolayer(simulation, .vars = .sim) +
  geom_line() +
  theme(legend.position = "none") +
  labs(y = "Working Capital (millions)", x = "Date")
```

# Date Table

### Date Table

```{r, table, echo=FALSE}
three_yr_forecast <- forecast(full_fit, h = "3 year") %>%
  hilo(95) %>%
  as_tibble() %>%
  select(date, .mean, '95%') %>%
  rename(forecast = .mean) %>%
  rename(conf_int = '95%') %>%
  unpack_hilo(conf_int)

three_yr_forecast$conf_int_lower <-
  round(three_yr_forecast$conf_int_lower, 3)
three_yr_forecast$conf_int_upper <-
  round(three_yr_forecast$conf_int_upper, 3)
three_yr_forecast$forecast <- round(three_yr_forecast$forecast, 3)
three_yr_forecast$date <- as.Date(three_yr_forecast$date)

datatable(
  three_yr_forecast,
  class = 'cell-border stripe',
  colnames = c("Date", "Forecast", "Lower bound", "Upper bound"),
  caption = "Point forecast for working capital levels"
)
```

```{r}
# # making some fake data
# set.seed(42)
# date <- seq(as.Date("2010-01-01"), as.Date("2020-01-01"), "weeks")
# # x <- rnorm(n = length(date), mean = 10, sd = 5)
# # y <- x * 2 + 10 * rnorm(length(date))
# time_series_data <- function(mean, sd) {
#   # should make this more seasonal
#   column <- c(0)
#   for (i in 1:length(date)) {
#     if (i %% 7 == 0) {
#       column <- c(column, column[i - 1] + rnorm(1, 7, 2))
#     } else{
#       column <- c(column, column[i - 1] + rnorm(1, mean, sd))
#     }
#   }
#   return(column)
# }
# current_assets <- time_series_data(2, 30)
# current_liabilities <- time_series_data(1, 20)
```




