---
title: "Price Elasticity Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    css: styles-default.css
    logo: logo.png
runtime: shiny
---

```{r setup, include=FALSE}

# 1.0 LIBRARIES ----

#Shiny
library(flexdashboard)
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(DT)

#Core
library(tidyverse)
library(ggplot2)
library(plotly)
library(infer)
library(readxl)
```

```{r}

# 1.1 LOADING DATA ----

#sourcing my code
source("../R/cleaning_data.R")
source("../R/map_template.R")
source("../R/joining_tables.R")

#importing data
descriptions_path <- "../data/raw_data_cereal_descriptions.xlsx"
prices_path <- "../data/raw_data_cereal_prices.xlsx"
store_locations_path <- "../data/demo.dta"
us_locations_path <- "../data/uszips.xlsx"
illinois_map_path <- "https://raw.githubusercontent.com/empet/Datasets/master/illinois-election.geojson"

descriptions_tbl <- readRDS(file = "../R/descriptions_tbl.rds")
prices_tbl <- readRDS(file = "../R/prices_tbl.rds")
store_locations_tbl <- readRDS(file = "../R/store_locations_tbl.rds")
us_locations_tbl <- readRDS(file = "../R/us_locations_tbl.rds")
dates_tbl <- readRDS(file = "../R/dates_tbl.rds")

illinois_map <- readRDS(file = "../R/illinois_map.rds")
```

```{r, include = FALSE}
source("../R/joining_tables.R")

#obtaining our data tables
filtered_store_locations_tbl <- readRDS(file = "../R/filtered_store_locations_tbl.rds")
top_three_brands_tbl <- readRDS(file = "../R/top_three_brands_tbl.rds")
```

```{r, include = FALSE}
source("../R/joining_tables.R")
source("../R/modified_datasets.R")

#obtaining our data tables
sales_tbl <- readRDS(file = "../R/sales_tbl.rds")
sales_sample_tbl <- readRDS(file = "../R/sales_sample_tbl.rds")
total_tbl <- readRDS(file = "../R/total_tbl.rds")
```

```{r, include = FALSE}
#source code to plot the violin plot
source("../R/visual_understand_data.R")
```

```{r, include = FALSE}
#source code to plot the fitted vs residual
source("../R/visual_elasticity_analysis.R")
```

```{r, include = FALSE}
#source code to plot the bootstrap
source("../R/visual_understand_data.R")
```

```{r, include = FALSE}
#source code to obtain a bootstrap and CI
source("../R/creation_of_model.R")

bootstrap_tbl <- readRDS(file = "../R/bootstrap_tbl.rds")
ci <- readRDS(file = "../R/ci.rds")
```


Page 1
==============================================

### About Elasticity


Page 2
==============================================

Sidebar {.sidebar}
----------------------------------------------

``` {r}
#Inputs
checkboxGroupButtons(inputId = "Cereal_brand",
                     label = h4("Select Cereal Brands:"),
                     choices = c("Wheaties", "Cinnamon Toast Crunch", "Kix"),
                     selected = c("Wheaties", "Cinnamon Toast Crunch", "Kix"),
                     direction = "vertical")

checkboxGroupButtons(inputId = "Year_choosen",
                     label = h4("Year Selected:"),
                     choices = c("1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997"),
                     selected = c("1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997"))

selectInput(inputId = "Store_location",
           label = h4("Select Store Location:"), 
           choices = filtered_store_locations_tbl %>% distinct(city),
           multiple = TRUE
)
```

```{r}
# Reset Button
actionButton(inputId = "reset",
             label = "Reset",
             icon = icon("sync"))

observeEvent(eventExpr = input$reset, handlerExpr = {
  updateCheckboxGroupButtons(session = session,
                           inputId = "Cereal_brand",
                           selected = c("Wheaties", "Cinnamon Toast Crunch", "Kix"))
  
  updateDateRangeInput(session = session,
                       inputId = "Year_choosen",
                       selected = c("1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997"))
  
  updateSelectInput(session = session,
                    inputId = "Store_location",
                    selected = NULL)
  
})
```

Row
----------------------------------------------

```{r}
# total_revenue is a reactive expression that computes the total revenue
# of the cereals selected in the time frame selected.

total_revenue <- reactive({
  total_tbl %>%
    filter(
      description %in% input$Cereal_brand,
      city %in% input$Store_location,
      `year(start)` %in% input$Year_choosen
    ) %>%
    mutate(revenue = sum(total_revenue)) %>%
    select(revenue)
  })

# If nothing is choosen in the menu, have revenue = 0
# If something is choosen in the menu, have the revenues added

# Also there is nothing in the tibble...
# It doesn't like all three variables in the filter()

renderPrint(total_revenue())
```

### Total Revenue {.value-box}

``` {r}

renderValueBox({
  valueBox(values = total_revenue())
})
  
```

### Total Quantity Sold {.value-box}

```{r}
# total_sales is a reactive expression that computes the total quantity sold
# of the cereals selected in the time frame selected.

total_sales <- reactive({
  compute_total_sales <- total_tbl %>%
    filter(description %in% input$Cereal_brand) %>%
    filter(city %in% input$Store_location) %>%
    filter(`year(start)` %in% input$Year_choosen) %>%
    select(sum_sales)
  })

renderValueBox({
  valueBox(total_sales())
})

```

### AVG Unit Price {.value-box}

```{r}
# avg_unit_price is a reactive expression that computes the avg unit price
# of the cereals selected over the time frame selected.

avg_unit_price <- reactive({
  compute_avg_unit_price <- total_tbl %>%
    filter(description %in% input$Cereal_brand) %>%
    filter(city %in% input$Store_location) %>%
    filter(`year(start)` %in% input$Year_choosen) %>%
    select(avg_price)
  })

renderValueBox({
  valueBox(avg_unit_price())
})

```


Column
----------------------------------------------

### Violin Plot

```{r}
# dataset is a reactive expression that interacts with cereal brands, dates, and store prices & sales.

dataset <- reactive({
  sales_tbl %>%
    filter(description %in% input$Cereal_brand) %>%
      filter(city %in% input$Store_location) %>%
        filter(`year(start)` %in% input$Year_choosen) %>%
    select(sales, price)
})

# renderTable(dataset())

# Violin Plot for Sales
plotlyOutput("violin_sales_plot")

output$violin_sales_plot <- renderPlotly({
  data = dataset()
  plot_violin_sales(data, "Brand Names", "Sales of Cereal Boxes", "Distribution of Sales by Brand")
})

# Violon Plot for Prices

plotlyOutput("violin_price_plot")

output$violin_price_plot <- renderPlotly({
  data = dataset()
  plot_violin_price(data, "Brand Names", "Price of Cereal Boxes", "Distribution of Prices by Brand")
})
```

Column
----------------------------------------------

### Bar Graph

```{r}
# total_dataset is a reactive expression that interacts with cereal brands, dates, and store prices & sales.

total_dataset <- reactive({
  total_tbl %>%
    filter(description %in% input$Cereal_brand) %>%
      filter(city %in% input$Store_location) %>%
        filter(year(start) %in% input$Year_choosen) %>%
    select(sales, price)
})

# renderTable(total_dataset())

# Bar Graph of Revenue by City
plotlyOutput("bar_revenue_plot")

output$bar_revenue_plot <- renderPlotly({
  total = total_dataset()
  plot_total_revenue_bar(total)
})
```


### Line Graph

```{r}
# Line Graph of Revenue by Time
plotlyOutput("line_revenue_plot")

output$line_revenue_plot <- renderPlotly({
  total = total_dataset()
  plot_total_revenue_line(total)
})
```

Page 3
==============================================

Sidebar {.sidebar}
----------------------------------------------

``` {r}
#Inputs
checkboxGroupButtons(inputId = "Cereal_brand",
                   label = h4("Select Cereal Brands:"),
                   choices = c("Wheaties", "Cinnamon Toast Crunch", "Kix"),
                   selected = c("Wheaties", "Cinnamon Toast Crunch", "Kix"),
                   direction = "vertical")

sliderInput(inputId = "alpha",
            label = h4("Select Alpha:"),
            min = 0.80,
            max = 0.95,
            value = 0.95,
            step = 0.05,
            pre = "%")
```

```{r}
# Reset Button
actionButton(inputId = "reset",
             label = "Reset",
             icon = icon("sync"))

observeEvent(eventExpr = input$reset, handlerExpr = {
  
  updateCheckboxGroupButtons(session = session,
                           inputId = "Cereal_brand",
                           selected = c("Wheaties", "Cinnamon Toast Crunch", "Kix"))
  
  updateSliderInput(session = session,
                    inputId = "alpha",
                    value = .95)
})
```

Column {data-width = 500}
----------------------------------------------

### Elasticity Analysis

```{r}
# Bootstrap plot
reactive_alpha <- reactive({
  new_ci_tbl <- bootstrap_tbl %>%
    mutate(perc_ci = purrr::map(bootstrap_slopes, get_confidence_interval, level = input$alpha, type = 'percentile')) %>%
    unnest(perc_ci)
})

# renderTable(reactive_alpha())
plotlyOutput("bootstrap_plot")

output$bootstrap_plot <- renderPlotly({
  data = reactive_alpha()
  plot_bootstrap(data)
})
```



